<?php
/**
 * Plugin Name: Glassmorphism Nav Elementor
 * Description: Adds a glassmorphism bottom-docked navigation Elementor widget.
 * Version: 1.0.0
 * Author: Generated by GitHub Copilot
 * Text Domain: glassmorphism-nav-elementor
 * Domain Path: /languages
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

final class Glassmorphism_Nav_Elementor {
    const VERSION = '1.0.0';
    const MINIMUM_ELEMENTOR_VERSION = '3.0.0';
    const MINIMUM_PHP_VERSION = '7.4';

    public function __construct() {
        add_action( 'init', array( $this, 'init' ) );
        add_action( 'elementor/widgets/widgets_registered', array( $this, 'register_widget' ) );
        add_action( 'wp_enqueue_scripts', array( $this, 'register_assets' ) );
        add_action( 'admin_notices', array( $this, 'admin_notice_required_plugins' ) );
    }

    public function init() {
        if ( version_compare( PHP_VERSION, self::MINIMUM_PHP_VERSION, '<' ) ) {
            return;
        }

        if ( ! did_action( 'elementor/loaded' ) ) {
            return;
        }

        load_plugin_textdomain( 'glassmorphism-nav-elementor', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );
    }

    public function register_widget() {
        if ( ! did_action( 'elementor/loaded' ) ) {
            return;
        }

        require_once __DIR__ . '/includes/widgets/class-widget-glassmorphism-nav.php';

        
        \Elementor\Plugin::instance()->widgets_manager->register_widget_type( new \Glassmorphism_Nav_Widget() );
    }

    public function register_assets() {
        wp_register_style(
            'glassmorphism-nav-elementor-style',
            plugins_url( 'assets/css/nav-widget.css', __FILE__ ),
            array(),
            self::VERSION
        );

        wp_register_style(
            'glassmorphism-nav-elementor-fontawesome',
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css',
            array(),
            '6.4.0'
        );

        wp_register_script(
            'glassmorphism-nav-elementor-gsap',
            'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js',
            array(),
            '3.12.2',
            true
        );

        wp_register_script(
            'glassmorphism-nav-elementor-script',
            plugins_url( 'assets/js/nav-widget.js', __FILE__ ),
            array( 'glassmorphism-nav-elementor-gsap' ),
            self::VERSION,
            true
        );
    }

    public function admin_notice_required_plugins() {
        if ( defined( 'ELEMENTOR_VERSION' ) ) {
            return;
        }

        if ( ! current_user_can( 'activate_plugins' ) ) {
            return;
        }

        $class   = 'notice notice-error';
        $message = __( 'Glassmorphism Nav Elementor requires Elementor to be installed and activated.', 'glassmorphism-nav-elementor' );

        printf( '<div class="%1$s"><p>%2$s</p></div>', esc_attr( $class ), esc_html( $message ) );
    }
}

new Glassmorphism_Nav_Elementor();
